AlexFlipnote/Discord_Theme

theme.css
=> that typo tho

theme.css
Was literally one pixel off which was driving me mad, accept PR, thanks.
=> General CSS Fixes

theme.css
+ Dark Search Popup
+ Dark Search Date Picker
Preview:
http://i.imgur.com/dQRIDHN.gifv
=> Added Dark Search Menu

theme.css
+ The Keyboard Combos page is now more fitting to the theme.
Preview:
http://i.imgur.com/qfDaCad.gifv
=> Added Dark Keyboard Combos

theme.css
Fixes ![Archer's Keyboard Combos](http://i.imgur.com/7JHyQn1.png)
Fixes Role selector in Channel permissions being in place of server settings bubble
=> Server Settings Bubble Patch

theme.css
=> Channel Notices

assets/wideGuilds.css
The friends icon seemed to be off, turns out I hecced up the alignment along the line somewhere. This should fix.
=> Fixed a small bug

theme.css
=> Upload Makeover

assets/autoMemberlist.css
=> fixed the emoji icon showing over the member list

assets/autoMemberlist.css
=> made the role name disappear when the members list isn't hovered

theme.css
=> Emoji Picker Makeover

theme.css
I won't provide screenshots this time, the file drop menu is broken on Japanese, 
but I made sure it worked in English. 
But don't worry, Discord is on the works.
https://trello.com/c/TNsHzbd0
=> Upload Drop Makeover, and a few other changes.

assets/transparent.css, theme.css
The small faint background square behind the guilds annoyed me, and that accent behind the icons was unnecessary, so here you go.
=> Guild Wrapper Fix

Plugins.md
Added two new plugins in Plugins.md :)
=> Updated Plugins.md

assets/CodeblockHeight.css, assets/highlightJS.css
Somehow Firacode doesn't seem to work on my end. If anyone else is also having this, report it as an [issue](https://github.com/alexflipnote/discord_theme/issues)
=> Fix code block colors being black

Plugins.md, assets/hideSearch.css, theme.css
=> Hide search bar

theme.css
New location: ![image](https://light-theme-hurts.my-ey.es/6cd353.png)
=> Fix typo, pull down Voice Connected Icon

theme.css
Before: ![](https://light-theme-hurts.my-ey.es/45ed74.png)
After: ![](https://light-theme-hurts.my-ey.es/1561cb.png)
=> Pull down the voice connected icon a little bit more

README.md
=> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

theme.css
Moved the catagory panel to the left side to be more language friendly, as it seems Discord is being quite slow on that. Moved the avatar and text beside it up to the top bar for a more clean look, also in a response so it doesn't shove itself into the text.
=> Profile Modal changes

Plugins.md, theme.css
```css
:root{
--nsfw-image: url("https://example.com/image.png");
}```
=> Make the image shown as NSFW image configurable

theme.css
Thought it'd be more nice to keep it more vanilla friendly towards the theme.
=> Some color changes

assets/defDarkColors.css, theme.css
This is the best I could pull off, codeblocks are really fucky.
(And again I forget to mention the colour changes.)
=> Code block changes, and changes to the default colour addon which wasn't default.

Plugins.md, assets/BA-D.css
Added BetterAnimations to plugins.md
=> Added BetterAnimations

README.md
=> Update README.md theme.css to bold

assets/wideGuilds.css
With this plugin, it is a little out of whack. http://i.imgur.com/apMBGn7.png This will delete it all together: http://i.imgur.com/6jTv89M.png
=> Delete "public" button

theme.css
=> statuses are nice, and other fixes

theme.css
=> context menu submenu arrows

assets/transparent.css
=> fix white title bar

assets/transparent.css
=> transparent.css: Fix friends bar

scss/components/_popout.scss, scss/components/_search.scss, theme.css
=> Search bar and Screeenshare popout fixes

scss/components/_global.scss, scss/components/_keyframes.scss, scss/components/_popout.scss, theme.css
=> add spotify styling

scss/components/_chat.scss, scss/components/_search.scss, scss/components/_settings.scss, theme.css
- fix search css & calendar
- fix channnel notices
- clean css
- add change notice
=> Search bar fixes and other fixes

autotheme.css
adding the imports under root didn't work anymore.
and added the other text to let people know its possible
=> clarifications
